const branchCodes = {
'Aguilar': 'AG',
'Allerton':'AL',
'Battery Park': 'BT',
'Bookmobile 1':'B1',
'Bookmobile 2':'B2',
'Bookmobile 3':'B3',
'Baychester' : 'BA',
'Belmont': 'BE',
'City Island': 'CI',
"Clason's Point": 'CP',
'Castle Hill': 'CT',
'Chatham Square':'CH',
'Columbus':'CS',
'Dongan Hills':'DH',
'Spuyten Duyvil': 'DY',
'Eastchester': 'EA',
'Edenwald': 'EW',
'E-Branch':'EB',
'Bronx Library Center': 'BC',
'Francis Martin': 'FX',
'Grand Concourse': 'GD',
'Grand Central': 'GC',
'George Bruce':'BR',
'High Bridge': 'HB',
"Hunt's Point": 'HS',
'Jerome Park': 'JP',
'Kingsbridge': 'KB',
'LSC Educator Collection': 'ED',
'Melrose': 'ME',
'Mott Haven': 'MH',
'Mosholu': 'MO',
'Morris Park': 'MP',
'Morrisania': 'MR',
'Parkchester': 'PK',
'Pelham Bay': 'PM',
'Riverdale': 'RD',
'Sedgwick': 'SD',
'Soundview': 'SV',
"Throg's Neck": 'TG',
'Tremont': 'TM',
'Van Cortlandt': 'VC',
'Van Nest': 'VN',
'Pelham Parkway-Van Nest':'VN',
'West Farms': 'WF',
'Wakefield': 'WK',
'Woodlawn Heights': 'WL',
'Woodstock': 'WO',
'Westchester Square': 'WT',
'Bloomingdale': 'BL',
'Terrence Cardinal Cooke-Cathedral': 'CA',
'Morningside Heights': 'CL',
'Epiphany':'EP',
'58th Street': 'FE',
'Fort Washington': 'FW',
'125th Street':'HD',
'One Hundred Twenty-Fifth Street':'HD',
'Hamilton Fish Park': 'HF',
'Hamilton Grange': 'HG',
'Harlem': 'HL',
'Hudson Park': 'HP',
'Countee Cullen':'HT',
'115th Street':'HU',
'One Hundred and Fifteenth Street': 'HU',
'Inwood':'IN',
'Jefferson Market': 'JM',
'Kips Bay':'KP',
'New Amsterdam':'LM',
"Macomb's Bridge": 'MB',
'Mulberry Street':'ML',
'Muhlenberg':'MU',
'96th Street':'NS',
'Ninety-sixth':'NS',
'Ottendorfer':'OT',
'Roosevelt Island':'RI',
'Riverside':'RS',
'St. Agnes': 'SA',
'Seward Park':'SE',
'67th Street':'SS',
'Tompkins Square':'TS',
'Webster':'WB',
'Washington Heights': 'WH',
'Great Kills':'GK',
'Huguenot Park':'HK',
'West New Brighton':'NB',
'New Dorp':'ND',
'Port Richmond':'PR',
'Richmondtown':'RT',
'South Beach':'SB',
'St. George':'SG',
'Stapleton':'ST',
'Terence Cardinal Cooke-Cathedral':'CA',
'Todt Hill-Westerleigh':'TH',
'Tottenville':'TV',
"Mariner's Harbor": 'MN',
'Donnell Library Center':'DLC',
'Andrew Heiskell':'LB',
'Mid-Manhattan':'MM',
'Stavros Niarchos Foundation Library': 'SN',
'Performing Arts': 'MY',
'Performing Arts Library at Lincoln Center':'MY',
'Science Industry and Business': 'SL',
'SIBL - Science Industry and Business': 'SL',
'Humanities and Social Sciences': 'CRL',
"NYPL Children's Center @ 42nd": 'MAJ',
// 'SASB':'CC',
'World Land Orders':'CCD',
'53rd Street': 'FT',
'Fifty-Third':'FT',
'Electronic Materials for Adults':'IA',
'Research Electronic Materials for Adults':'IARCH',
'SIBL Research Electronic Material for Adults':'IASLR',
'Electronic Material for Children':'IJ',
'Library Services Center':'LS',
'Stephen A. Schwarzmann Building':'MA',
'SASB':'MA',
'OFF SITE - ReCAP Partner':'OS',
'NYCHA Collection':'NYY',
'NYCHA':'NYJ',
'NYPL Research Libraries':'RC',
'Schomburg Center':'SC',
'39th ST - HR - Finance - Marketing':'TN',
'Inter-Library Loan':'XFILL',
'Collection Rebalancing':'XR',
'Research Libraries - On Order': 'XXX',
'Yorkville':'YV',
}

export default branchCodes;
